export function generateCollectionPDF(items, stats) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 15;
    let y = 20;

    // Title
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('PitchKing Collect', margin, y);
    y += 8;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text('Collection Report', margin, y);
    y += 4;
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, margin, y);
    y += 12;

    // Stats summary
    doc.setDrawColor(0, 212, 255);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;

    doc.setFontSize(11);
    doc.setTextColor(0);
    doc.setFont('helvetica', 'bold');
    doc.text('Collection Summary', margin, y);
    y += 7;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const summaryLines = [
        `Total Items: ${stats.total}`,
        `Graded Items: ${stats.graded}`,
        `Average Grade: ${stats.avgGrade > 0 ? stats.avgGrade.toFixed(1) : 'N/A'}`,
        `Estimated Value: ${stats.totalValue > 0 ? '$' + stats.totalValue.toFixed(2) : 'Not estimated'}`,
        `Brands: ${stats.brands.join(', ') || 'N/A'}`,
        `Sports: ${stats.sports.join(', ') || 'N/A'}`,
    ];
    for (const line of summaryLines) {
        doc.text(line, margin, y);
        y += 5;
    }
    y += 8;

    // Table header
    doc.setDrawColor(0, 212, 255);
    doc.line(margin, y, pageWidth - margin, y);
    y += 6;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);

    const cols = [
        { label: '#', x: margin, w: 8 },
        { label: 'Name', x: margin + 8, w: 40 },
        { label: 'Brand', x: margin + 48, w: 25 },
        { label: 'Year', x: margin + 73, w: 15 },
        { label: 'Set', x: margin + 88, w: 30 },
        { label: 'Type', x: margin + 118, w: 20 },
        { label: 'Team', x: margin + 138, w: 20 },
        { label: 'Grade', x: margin + 158, w: 12 },
        { label: 'Value', x: margin + 170, w: 15 },
    ];

    for (const col of cols) {
        doc.text(col.label, col.x, y);
    }
    y += 3;
    doc.setLineWidth(0.3);
    doc.line(margin, y, pageWidth - margin, y);
    y += 4;

    // Table rows
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(30);

    for (let i = 0; i < items.length; i++) {
        if (y > 275) {
            doc.addPage();
            y = 20;
        }

        const item = items[i];
        const row = [
            String(i + 1),
            truncate(item.item_name || 'Unknown', 22),
            truncate(item.brand || '', 14),
            item.year ? String(item.year) : '',
            truncate(item.set_name || '', 16),
            truncate(item.subset || '', 11),
            truncate(item.team || '', 11),
            item.overall_grade ? item.overall_grade.toFixed(1) : '',
            item.estimated_value ? '$' + item.estimated_value.toFixed(0) : '',
        ];

        for (let c = 0; c < cols.length; c++) {
            doc.text(row[c], cols[c].x, y);
        }

        // Alternate row shading
        if (i % 2 === 0) {
            doc.setFillColor(245, 245, 250);
            doc.rect(margin, y - 3.5, pageWidth - margin * 2, 5, 'F');
            // Re-draw text on top of shading
            doc.setTextColor(30);
            for (let c = 0; c < cols.length; c++) {
                doc.text(row[c], cols[c].x, y);
            }
        }

        y += 5;
    }

    // Footer
    y += 8;
    doc.setDrawColor(0, 212, 255);
    doc.line(margin, y, pageWidth - margin, y);
    y += 6;
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text('Generated by PitchKing Collect — pitchkingcollect.com', margin, y);

    doc.save('PitchKing_Collection_Report.pdf');
}

function truncate(str, maxLen) {
    if (!str) return '';
    return str.length > maxLen ? str.substring(0, maxLen - 1) + '…' : str;
}
